#define XSLISAPI_FILEVERSION_NUM        0,0,0,0
#define XSLISAPI_FILEVERSION_STR        "0.0.0.0\0"
#define XSLISAPI_PRODUCTVERSION_NUM     0,0,0,0
#define XSLISAPI_PRODUCTVERSION_STR     "0.0.0.0\0"
